### ISSUE TITLE
项目启动的时候不能自动创建数据表

### ISSUE THREAD

**Issue by Katsuya623** [wellzhi/springboot-flowable#5]
![image](https://user-images.githubusercontent.com/32605379/155649796-38c4f4c5-641b-49a0-9163-d39e4c429d8f.png)

**Comment by wellzhi** [comment]
解决方案一
把正常的数据库的表导出为[sql](https://so.csdn.net/so/search?q=sql&spm=1001.2101.3001.7020)，手动创建表。

解决方案二(推荐)
[mysql](https://so.csdn.net/so/search?q=mysql&spm=1001.2101.3001.7020)的连接字符串中添加上nullCatalogMeansCurrent=true，将schema默认设置为当前连接的schema。
